name: build-env
channels:
  - conda-forge
  # - anaconda
  # - main
dependencies:
  # Core modules (mandatory)
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.5.0,<0.6
  
  - jupyterlab~=4.3.4
  - python-libarchive-c >= 5.2
  - mamba == 1
  - watchfiles

  # C Linked Libraries #########################
  
  # # - gcc
  # # - gcc_linux-64    # https://stackoverflow.com/questions/53426235/unable-to-install-gcc-using-anaconda
  # # - gxx_linux-64
  # - cxx-compiler    # https://stackoverflow.com/questions/69485181/how-to-install-g-on-conda-under-linux
  # - c-compiler      # https://anaconda.org/conda-forge/c-compiler/
  # - cmake
  # # - cmake-binary    # cmake and cmake-binary
  # # - pkg-config
  # - pkgconfig       # https://github.com/conda-forge/pkgconfig-feedstock
  # - zlib            # https://github.com/conda-forge/zlib-feedstock
  # - libzlib
  # # - zlib-wapi
  # # - libzlib-wapi

  # Dynamic Linked Libraries ####################

  # - cairo         # https://github.com/conda-forge/cairo-feedstock
  # # - r-cairo       # https://github.com/conda-forge/r-cairo-feedstock
  # - expat         # https://github.com/conda-forge/expat-feedstock
  # - libexpat
  # - xorg-xproto   # https://github.com/conda-forge/xorg-xproto-feedstock
  # - xorg-kbproto  # https://github.com/conda-forge/xorg-kbproto-feedstock

  # Jupyter Kernel
  - jupyterlite-pyodide-kernel>=0.5.0     # Python kernel (optional)
  - jupyterlite-xeus>=3.0.0,<4
  # - jupyterlite-xeus-r
  - ipykernel
  - r-coursekata        # https://coursekata.org/


  # Jupyter Extensions ##########################
  - notebook~=7.3.2
  - jupyterlab_miami_nights       # JupyterLab: Miami nights theme (optional)
