name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.5.0,<0.6
  - jupyterlite-xeus>=3.0.0,<4
  - jupyterlite-pyodide-kernel

  - python-libarchive-c
  - jupyterlab_server
  - mamba == 1
